In [1]:
import numpy as np

[[1, 0], [2, -1]].

In [2]:
matriz = np.matrix([ 1, 0, 2, -1])

In [3]:
matriz

matrix([[ 1,  0,  2, -1]])

In [6]:
matriz = np.array([[1,0], [2,-1]])

In [7]:
matriz

array([[ 1,  0],
       [ 2, -1]])

In [8]:
lista = [[1, 0],
        [2, -1]]

In [9]:
matriz = np.array(lista)

In [10]:
matriz

array([[ 1,  0],
       [ 2, -1]])

In [12]:
matriz[1,:]

array([ 2, -1])

In [13]:
# Generad una lista de 100 valores enteros aleatorios de 0-9.
np.random.randint(0,9,100)

array([3, 8, 5, 1, 0, 7, 0, 6, 2, 7, 5, 3, 0, 0, 2, 4, 8, 4, 8, 2, 1, 4,
       2, 8, 3, 0, 0, 8, 5, 6, 4, 5, 1, 0, 3, 7, 1, 6, 0, 4, 1, 4, 8, 8,
       0, 3, 7, 1, 5, 1, 7, 6, 0, 3, 8, 8, 3, 8, 5, 1, 6, 2, 3, 2, 5, 2,
       7, 3, 8, 8, 0, 1, 1, 0, 5, 2, 3, 6, 1, 7, 1, 3, 8, 0, 8, 1, 2, 2,
       8, 0, 3, 8, 5, 7, 2, 3, 3, 0, 2, 1])