

## entorno SciPy
Es un ecosistema basado en Python de sofware abierto para las matematicas, ciencias e ingeniería. En particular estos son algunos de sus principales paquetes: 
https://www.scipy.org/

- **numpy** es para la parte de array o n dimensiones
https://numpy.org/

- **scipy** para fundamentos cientificos
- **matplotlib** para graficos
- **sympy** simbolos matematicos
- **ipython** jupyter está basado en esto
- **pandas** estructura de datos y análisis


hay una capa o framework
las librerias tienen dependencias

## Unidad Python NumPy


In [2]:
# importamos la libreria. la llamamos np para no estar todo el rato escribiendo numpy
import numpy as np
np.__version__

'1.18.5'

En data science usamos modelos. 
1ª capa: extracción, transformación y manipulación, carga: pandas, intake, pyjanitor
2ª capa: exploratory analysis: Jypyter, Seaborn, Matplotlib, Altail (este es el 99% de nuestro trabajo, hay que documentar todo).
3ª capa. Model and evaluate: scikit-learn, statsmodels, PyMC3, spaCy
4ª capa. Report in a dashboard: Dash, Panel, Voila


En `NumPy` el objeto básico se trata de una lista multidimensional de números normalmente del mismo tipo. 

In [5]:
# Ejemplo
p = np.array([1, 2, 3]) # el array es como una lista de elementos
p

array([1, 2, 3])

In [6]:
# de la misma forma que lo realizamos con list utilizamos los íncices para extraeer el valor
p[1]

2

In [9]:
# Analizamos el tipo de objeto
type(p)

numpy.ndarray

En *NumPy*, a las dimensiones se les conoce con el *nombre de ejes (axes)* y al *número se le dice rango (rank)*. 

Array es un alias para referirse al tipo de objeto *numpy.ndarray*

Tenemos algunas de las propiedades de los **arrays**
- *ndarray.ndim* : es el número de ejes del objeto array (matriz)
- *ndarray.shape* : devuelve una tupla de números enteros indicando longitud de las dimensiones de la matriz
- *ndarray.size* : devuelve el número total de elementos de una matriz

In [35]:
# Ejemplo de una matriz 3x2 (3 filas y 2 columnas) 
# aquí veo un vector unidimensional 

a = np.arange(3*2) # con esta función creamos la estructura unidimensional de 6 elementos 
print("Array unidimensional: ")
print(a)

Array unidimensional: 
[0 1 2 3 4 5]


In [36]:
# si quiero darle una forma de matriz 3x2 utilizo la función `reshape()`
# aquí veo una matriz con su propia estructura

a =a.reshape(3,2)
print("Matriz 3x2:")
print(a)

Matriz 3x2:
[[0 1]
 [2 3]
 [4 5]]


In [13]:
type(a) # en realidad sigue siendo un array

numpy.ndarray

In [21]:
# vemos una posición del array
print(a[1]) # extraemos solo la segunda fila (posicion 1 )
print(a[1,1]) # extraelmos el valor de la segunda fila y la segunda columna
a[1,1]

[2 3]
3


3

In [22]:
type(a[1]) # sigue siendo un array

numpy.ndarray

In [23]:
type(a[1,1]) # devuelve el tipo del valor extraido

numpy.int32

In [24]:
# dimensiones del array
a.ndim # devuelve el número de ejes

2

In [25]:
# longitud de las dimensiones (3 filas y dos columnas)
a.shape

(3, 2)

In [26]:
# número de los elementos
a.size

6

A la hora de crear un array, tenemos diferentes opciones

In [27]:
# creamos un array de diez elementos 
z = np.zeros(10) # zeros es una funcion nativa que crea vectores de ceros
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
type(z[1])

numpy.float64

In [29]:
# podemos cambiar cualquiera de los valores accediendo por su posición
z[4] = 5. # es lo mismo que escribir 5.0
z[-1] = .1 # es lo mismo que escribir 0.1
print(z) # nos devuelve un vector de float

[0.  0.  0.  0.  5.  0.  0.  0.  0.  0.1]


In [30]:
type(z)

numpy.ndarray

In [31]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
# cambiamos los valores de una matriz ya definida con range numPy, `arange`, marcando el inicio y el final
# arange se usa exactamente igual que range dentro del for
print(a)
a =np.arange(10,20) # incluimos el start 10 hasta 19
print(a)

[[0 1]
 [2 3]
 [4 5]]
[10 11 12 13 14 15 16 17 18 19]


In [38]:
type(a)

numpy.ndarray

In [39]:
# también podemos incluir los pasos con step
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [40]:
# Podemos crear arrays desde las listas de Python de varias dimensiones
# van dentro de [] y cada elemento también dentro de []
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


## Operaciones con matrices

Con `numPy`podemos implementar todas las operaciones habituales con matrices

In [41]:
# construimos dos matrices
A = np.array([[1,0],[0,1]])
B = np.array([[1,2],[3,4]])
C = np.array([[1,5],[6,4],[8,9]])
print(A)
print("*"*50)
print(B)
print("*"*50)
print(C)

[[1 0]
 [0 1]]
**************************************************
[[1 2]
 [3 4]]
**************************************************
[[1 5]
 [6 4]
 [8 9]]


In [42]:
# suma de matrices
print(A+B)

[[2 2]
 [3 5]]


In [43]:
# como A y C no tienen el mismo tamaño no se pueden sumar
print(A+C)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [44]:
# Resto de operaciones con matrices
print(A-B)

[[ 0 -2]
 [-3 -3]]


In [45]:
# multiplicación de matrices por elemento por elemento
print(A*B)

[[1 0]
 [0 4]]


In [46]:
# multiplicación de una matriz por otra matriz
print(A.dot(B))

[[1 2]
 [3 4]]


In [47]:
# Potencia 
print(B**2)

[[ 1  4]
 [ 9 16]]


## Slicing e Iteración

Los arrays de numPy soportan la técnica de `slicing`de Python.

In [48]:
# Creamos un array de 0 a 9
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
# Obtenemos los elementos de la posición 3 del array  al 5-1
print(b[2:5]) # siempre inicio y final -1

[2 3 4]


In [51]:
# Todos los elementos de la tercera posición en adelante
print(b[2:])

[2 3 4 5 6 7 8 9]


In [52]:
# Si queremos iterar por cada elemento
for i in b:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [53]:
# Creamos un array multidimensional
c = np.arange(18).reshape(6,3) # defino 18 valores de 6 filas y 3 columnas
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [54]:
# Accedemos a la posición 4ª fila y 3ª columna
print(c[3,2])

11


In [57]:
# Accedemos la posición 4ª fila y 3ª columna de forma alternativa

print(c[3][2])

11


In [58]:
# otra forma 
c[3,2]

11

In [59]:
# otra
c[3][2]

11

In [60]:
# imprimit fila completa 2
print(c[2])

[6 7 8]


In [61]:
# accedemos a la columna completa 1
print(c[:,0])

[ 0  3  6  9 12 15]


In [62]:
# Extraemos todas las filas hasta la 5a 
print(c[:5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [63]:
# vamos a iterar en un arrat multidimensional
c.shape[0]

6

In [65]:
## iteramos cada columna y luego cada fila, así vamos sacando uno a uno los elementos del array

for i in range(c.shape[0]): # aquí lo hará por 6 veces porque son 6 filas y 3 columnas, por eso se pone un 0
    for j in range(c.shape[1]): # aquí lo hará por 3 veces porque son 6 filas y 3 columnas, por eso se pone un 1
        print("Elemento: {}".format(c[i , j]))

Elemento: 0
Elemento: 1
Elemento: 2
Elemento: 3
Elemento: 4
Elemento: 5
Elemento: 6
Elemento: 7
Elemento: 8
Elemento: 9
Elemento: 10
Elemento: 11
Elemento: 12
Elemento: 13
Elemento: 14
Elemento: 15
Elemento: 16
Elemento: 17


In [66]:
# slicing en asgnaciones 
# cambio la posicion 3,2 por 42
c[3,2] = 42
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 42]
 [12 13 14]
 [15 16 17]]


In [67]:
# Realizamos el cambio en bloque como una fila completa
c[2] = [666, 666, 666]
print(c)

[[  0   1   2]
 [  3   4   5]
 [666 666 666]
 [  9  10  42]
 [ 12  13  14]
 [ 15  16  17]]


In [68]:
# Realizamos el cambio de todos los valores por N utilizamos (...)
d = c # hago primero un backup
d[...] = 0 # asigno a todos los valores el cero
print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### Ejemplo: El juego de la vida de Conway
El juego de la vida es un ejemplo clásico de autómata celular creado en 1970 por el famoso matemático John H. Conway. 
En el problema clásico, se representan en una matriz bidimensional células que vivirán o morirán dependiendo del número de vecinos en un determinado paso de la simulación. Cada célula tiene 8 vecinos (las casillas adyacentes en un tablero bidimensional) y puede estar viva (1) o muerta (0). Las reglas clásicas entre transición vida/muerte son las siguientes:
* Una célula muerta con exactamente 3 células vecinas vivas al turno siguiente estará viva.
* Una célula viva con 2 o 3 células vecinas vivas sigue viva. Si no es el caso, muere o permanece muerta (soledad en caso de un número menor a 2, superpoblación si es mayor a 3).
Este problema (o juego) tiene muchas variantes dependiendo de las condiciones iniciales, si el tablero (o mundo) tiene bordes o no, o si bien las reglas de vida o muerte son alteradas.
A continuación tenéis un ejemplo del juego clásico implementado en NumPy:

In [87]:
SIZE = 10
STEPS = 10

    
def iterate(Z):
    # cuenta los vecinos
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
# Creamos un tablero con células vivas o muertas de forma aleatoria.
Z = np.random.randint(0,2,(SIZE, SIZE))
# Simulamos durante los pasos indicados.
for i in range(STEPS):
    Z = iterate(Z)
# Mostramos el tablero en el paso final.
print(Z) 

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
