# Programación 201

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [1]:
# Respuesta. Lo primero que hacemos es importar la librería NumPy.
import numpy as np

In [2]:
# Creamos nuestra matriz.
matriz = np.array([[1,0], [2,-1]])

In [3]:
# Calculamos la norma con linalg.norm

np.linalg.norm(matriz)

2.449489742783178

In [4]:
# Y calculamos el determinante con linalg.det

np.linalg.det(matriz)

-1.0

### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [5]:
# Respuesta. Calculo el arcoseno de [0,1] y lo guardo en un array que llamo arcoseno

a = [0,1]
arcoseno = np.arcsin(a)

In [6]:
# Y hago lo mismo con el arcocoseno, guardándolo en otro array del mismo nombre. 

arcocoseno = np.arccos(a)

### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [7]:
# Respuesta. Para generar una lista de valores enteros aleatorios usamos np.random.randint(), donde se define el primer número, el último 
# y el tamaño de la lista. La voy a guardar en list1

list1 = np.random.randint(0,9,100)

In [8]:
# Comprobamos los valores de nuestra lista

list1

array([7, 2, 1, 8, 0, 1, 1, 7, 2, 0, 1, 8, 8, 3, 6, 8, 1, 5, 6, 3, 8, 3,
       7, 1, 1, 2, 7, 3, 6, 5, 5, 5, 0, 8, 3, 6, 3, 8, 5, 0, 8, 0, 4, 0,
       5, 1, 5, 8, 0, 1, 5, 3, 1, 1, 2, 5, 1, 3, 7, 4, 5, 8, 7, 1, 7, 3,
       6, 6, 4, 5, 5, 3, 6, 7, 8, 7, 3, 1, 7, 1, 5, 2, 4, 8, 6, 4, 8, 6,
       0, 6, 0, 3, 4, 1, 8, 6, 3, 6, 6, 6])

In [9]:
# calculo la media 

list1.mean()

4.2

In [10]:
# la desviación estandar 

list1.std()

2.6457513110645907

In [12]:
# El valor mínimo

np.amin(list1)

0

In [13]:
# El valor máximo 

np.amax(list1)

8

In [15]:
# sumar todos los valores de la lista

np.sum(list1)


420

In [16]:
# Conseguir una lista de valores únicos

np.unique(list1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [17]:
# Respuesta. Primero creo la matriz:
matriz2 = np.array([[5,1,7], [0,7,4], [7,23,1]])


In [25]:
# Y ordenamos los valores con sort de numpy. Primero los ordeno por columna con axis=0.
np.sort(matriz2, axis= 0, kind="mergesort")

array([[ 0,  1,  1],
       [ 5,  7,  4],
       [ 7, 23,  7]])

In [26]:
# Y también los ordeno por fila con axis=1
np.sort(matriz2, axis= 1, kind="mergesort")

array([[ 1,  5,  7],
       [ 0,  4,  7],
       [ 1,  7, 23]])

### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [29]:
# Respuesta. Primero creamos dos matrices A y B. 
A=np.array([[5,1,7], [0,7,4], [7,23,1]])
B=np.array([[-1,-2,0],[5,2,-2],[12,-7,0]])

# Habría que calcular el valor absoluto (np.absolute) de la multiplicación (np.dot) de los determinantes de A y B (np.linalg.det)
np.absolute(np.dot(np.linalg.det(A),np.linalg.det(B)))

45880.00000000004

### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [33]:
# Respuesta. Creo una matriz identidad sin usar numpy. Para ello creo una matriz vacía a la que llamo C y hago una función en la que si la posición 
#(i,j) si i=j sea 1 y si no sea 0. 
C=[]
for i in range(10):
    fila=[]
    for j in range(10):
        if i==j:
            num=1
        else: num=0
        fila.append(num)
    C.append(fila)
C

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

In [34]:
# Creamos una matriz identidad 10x10 usando el generador de matrices identidad de numpy
D= np.identity(10)
D

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
# Para comprobor si las matrices son iguales y que salga solo un True, uso all:
(C==D).all()

True

### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [68]:
# Respuesta. Como los valores en Python cuentan desde 0 y no desde 1, y no se puede dividir por 0, vamos a forzar los valores añadiéndole 1 
# para que sea la posición real y no la de Python. 
E=[]
for i in range(2):
    fila=[]
    for j in range(6):
        if i%2==0:
            num=((i+1)**2+(j+1))
        else: num=(i+1)/(((j+1)**2))
        fila.append(num)
    E.append(fila)
E

[[2, 3, 4, 5, 6, 7],
 [2.0, 0.5, 0.2222222222222222, 0.125, 0.08, 0.05555555555555555]]

### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [89]:
# Respuesta. Creo 2 matrices de 5X5 aleatorias
F= np.random.random((5,5))
F

array([[0.76242645, 0.71210399, 0.74741868, 0.28801458, 0.77961487],
       [0.46849664, 0.28694407, 0.41997258, 0.61448906, 0.84957207],
       [0.86841307, 0.47801286, 0.62770086, 0.88890619, 0.76344929],
       [0.34053075, 0.54097432, 0.6440545 , 0.97691959, 0.34635979],
       [0.98579959, 0.9481288 , 0.32542057, 0.17947118, 0.25921042]])

In [90]:
G=np.random.random((5,5))
G

array([[0.48249913, 0.55884749, 0.50063152, 0.62084357, 0.61291775],
       [0.23008606, 0.10802215, 0.25936533, 0.44463962, 0.14433229],
       [0.16781179, 0.28992018, 0.7762891 , 0.56237651, 0.83856282],
       [0.5212701 , 0.16841268, 0.16310617, 0.62097181, 0.75031909],
       [0.31954097, 0.8440923 , 0.95015842, 0.64913813, 0.59301746]])

In [91]:
# Multiplico las matrices
np.dot(F,G)

array([[1.05639325, 1.42626708, 1.93433736, 1.89523458, 1.87526989],
       [0.95433526, 1.235178  , 1.54244269, 1.58770255, 1.64561254],
       [1.3416418 , 1.51305433, 1.91639612, 2.15226607, 2.24732713],
       [1.01677149, 0.89235163, 1.29920118, 1.64563093, 1.76527638],
       [0.92478938, 0.99669926, 1.26761835, 1.49632176, 1.30232222]])

In [97]:
# otra forma de multiplicarlas        
            
def multimatriz(F,G):
    filasF=len(F)
    columnasF=len(F)
    columnasG=len(G)
    
    H =[[0 for j in range(columnasG)] for i in range(filasF)]
    
    for i in range(filasF):
        for j in range(columnasG):
            for k in range(columnasF):
                H[i][j] += H[i][k] * G[k][j]
    return H

In [95]:
H

[]

No consigo sacar el código para hacer la multiplicación manual de las matrices, estoy atascada y no sé por qué me sale la matriz resultante vacía. 